name: Update Imports

on:
  workflow_dispatch:

jobs:
  run-update-imports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run script
        env:
          FEEDONOMICS_API_KEY: ${{ secrets.FEEDONOMICS_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python getimportdetailsbulk.py
